import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home({ posts }) {
  console.log(posts);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1 className="text-3xl font-bold underline">DreamLaptops Blog</h1>
        {posts.nodes.map((post) => {
          return (
            <div key={post.slug}>
              <Link href={`/${post.slug}`}>
                <a>
                  <h2>{post.title}</h2>
                </a>
              </Link>
            </div>
          );
        })}
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch("https://dreamlaptops.com/graphql", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      query: `query NewQuery {
        posts {
          nodes {
            featuredImage {
              node {
                sourceUrl
              }
            }
            slug
            title
            content
          }
        }
      }`,
    }),
  });

  const data = await res.json();

  return {
    props: {
      posts: data.data.posts,
    },
  };
};
